services:
  app:
    build: .
    container_name: laundry-api
    ports:
      - "3000:3000"
    volumes:
      - db-data:/app/data
      - cabal-store:/root/.cabal
    working_dir: /app
    command: cabal run laundry-api
    environment:
      - TZ=America/Sao_Paulo

volumes:
  db-data:
  cabal-store:
  